##############################################
# Configuration options specific to camera 1 #
##############################################

# User defined name for the camera.
camera_name Cam1

# Numeric identifier for the camera.
camera_id 101

# Video device (e.g. /dev/video0) to be used for capturing.
video_device /dev/v4l/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.3:1.0-video-index0

# Text to be overlayed in the lower left corner of images
text_left CAM 1

# Text to be overlayed in the lower right corner of images.
text_right %Y-%m-%d\n%T-%q

# File name(without extension) for movies relative to target directory
movie_filename CAM01_%t-%v-%Y%m%d%H%M%S
